import React, { useState, Suspense } from 'react';
import { QueryClientProvider } from '@tanstack/react-query';
import { ReactQueryDevtools } from '@tanstack/react-query-devtools';
import { queryClient } from './lib/query-client';
import { useGenerateCollection } from './hooks/useGenerateCollection';
import { LandingPage } from './components/LandingPage';
import { TemplateSelectionScreen } from './components/TemplateSelectionScreen';
const InputStep = React.lazy(() => import('./components/wizard/InputStep'));
const PreviewStep = React.lazy(() => import('./components/wizard/PreviewStep'));
import { CubeLoader } from './components/CubeLoader';
import { SkeletonLoader } from './components/SkeletonLoader';
import { Template } from './types';
import { X, ChevronLeft } from 'lucide-react';

type AppScreen = 'landing' | 'template-selection' | 'wizard';
type LoadingPhase = 'idle' | 'cube' | 'skeleton' | 'result';

function CollectionWizard() {
  const [currentScreen, setCurrentScreen] = useState<AppScreen>('landing');
  const [loadingPhase, setLoadingPhase] = useState<LoadingPhase>('idle');
  const [templates, setTemplates] = useState<Template[]>([]);
  const [userPrompt, setUserPrompt] = useState('');
  const [error, setError] = useState<string | null>(null);

  const { mutate: generateCollection } = useGenerateCollection();

  const handleInputSubmit = (prompt: string, category?: string) => {
    setUserPrompt(prompt);
    setLoadingPhase('cube');
    setError(null);

    generateCollection(
      { userPrompt: prompt, category },
      {
        onSuccess: (data) => {
          setTimeout(() => {
            setLoadingPhase('skeleton');

            setTimeout(() => {
              setTemplates(data.templates);
              setLoadingPhase('result');
            }, 1500);
          }, 1500);
        },
        onError: () => {
          setLoadingPhase('idle');
          setError('Something went wrong. Please try again.');
        },
      }
    );
  };

  const handleRetry = () => {
    if (userPrompt) {
      handleInputSubmit(userPrompt);
    }
  };

  const handleClearPrompt = () => {
    setLoadingPhase('idle');
    setTemplates([]);
    setUserPrompt('');
    setError(null);
  };

  const handleBack = () => {
    setLoadingPhase('idle');
    setTemplates([]);
    setUserPrompt('');
    setError(null);
  };

  const handleSelectCollectionType = (typeId: string) => {
    if (typeId === 'group-gifts') {
      setCurrentScreen('template-selection');
      setLoadingPhase('idle');
      setError(null);
    }
  };

  const handleBackToLanding = () => {
    setCurrentScreen('landing');
    setLoadingPhase('idle');
    setTemplates([]);
    setUserPrompt('');
    setError(null);
  };

  const handleBackToTemplateSelection = () => {
    setCurrentScreen('template-selection');
    setLoadingPhase('idle');
    setTemplates([]);
    setUserPrompt('');
    setError(null);
  };

  const defaultTemplateFields = {
    suggestedAmounts: [25, 50, 100],
    customAmountEnabled: true,
    theme: { primaryColor: '#FF6B35', accentColor: '#F4A261' },
  };

  const handleSelectAICreator = () => {
    setCurrentScreen('wizard');
    setLoadingPhase('idle');
    setError(null);
    setTemplates([
      {
        id: 'ai-generated',
        title: 'AI Generated Collection',
        description: 'A collection generated by AI.',
        category: 'ai',
        ...defaultTemplateFields,
      },
    ]);
  };

  const handleSelectScratch = () => {
    setCurrentScreen('wizard');
    setLoadingPhase('idle');
    setError(null);
    setTemplates([
      {
        id: 'scratch',
        title: 'Custom Collection',
        description: 'Start from scratch.',
        category: 'custom',
        ...defaultTemplateFields,
      },
    ]);
  };

  const handleSelectTemplate = (templateId: string) => {
    // Find the template from TemplateSelectionScreen's templates
    const allTemplates = [
      {
        id: 'wedding-gift',
        title: 'Wedding Gift',
        description: 'A wedding gift collection.',
        category: 'wedding',
        ...defaultTemplateFields,
      },
      {
        id: 'baby-shower',
        title: 'Secret! Baby Shower + Gift',
        description: 'A baby shower collection.',
        category: 'baby',
        ...defaultTemplateFields,
      },
      {
        id: 'volleyball-coach',
        title: 'Volleyball Coach Gift',
        description: 'A volleyball coach gift collection.',
        category: 'coach',
        ...defaultTemplateFields,
      },
      {
        id: 'coworker-retirement',
        title: 'Coworker Retirement Lunch + Gift',
        description: 'A retirement collection.',
        category: 'retirement',
        ...defaultTemplateFields,
      },
      {
        id: 'staff-appreciation',
        title: 'Staff Appreciation Superheroes',
        description: 'A staff appreciation collection.',
        category: 'staff',
        ...defaultTemplateFields,
      },
      {
        id: 'secret-santa',
        title: 'Secret Santa Sign Up Sheet',
        description: 'A secret santa collection.',
        category: 'santa',
        ...defaultTemplateFields,
      },
      {
        id: 'end-of-year',
        title: 'End-of-Year Staff Giving',
        description: 'An end-of-year giving collection.',
        category: 'giving',
        ...defaultTemplateFields,
      },
      {
        id: 'birthday-surprise',
        title: 'Birthday surprises!',
        description: 'A birthday surprise collection.',
        category: 'birthday',
        ...defaultTemplateFields,
      },
    ];
    const selected = allTemplates.find((t) => t.id === templateId);
    if (selected) {
      setTemplates([selected]);
    } else {
      setTemplates([]);
    }
    setCurrentScreen('wizard');
    setLoadingPhase('idle');
    setError(null);
  };

  if (currentScreen === 'landing') {
    return <LandingPage onSelectType={handleSelectCollectionType} />;
  }

  if (currentScreen === 'template-selection') {
    return (
      <TemplateSelectionScreen
        onSelectAICreator={handleSelectAICreator}
        onSelectScratch={handleSelectScratch}
        onSelectTemplate={handleSelectTemplate}
        onBack={handleBackToLanding}
      />
    );
  }

  // Only render PreviewStep if templates are present and loadingPhase is 'result'
  if (loadingPhase === 'result' && templates.length > 0) {
    return (
      <div className="min-h-screen bg-cheddar-gray-50">
        {/* Navigation Header */}
        <div className="border-b border-cheddar-gray-200 bg-white">
          <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-4 flex items-center justify-between">
            <button
              onClick={handleBack}
              className="flex items-center gap-1 text-cheddar-orange hover:text-cheddar-orange-hover transition-colors text-sm font-medium"
            >
              <ChevronLeft className="w-4 h-4" />
              Previous
            </button>
            <div className="ml-auto flex items-center gap-4">
              <button
                onClick={handleBackToTemplateSelection}
                className="text-cheddar-orange hover:text-cheddar-orange-hover transition-colors text-sm font-medium"
              >
                Back to Dashboard
              </button>
              <img src="/Logo.png" alt="CheddarUp" className="h-8 w-auto" />
            </div>
          </div>
        </div>
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-12">
          <Suspense fallback={<div>Loading...</div>}>
            <PreviewStep
              templates={templates}
              userPrompt={userPrompt}
              onClearPrompt={handleClearPrompt}
            />
          </Suspense>
        </div>
      </div>
    );
  }

  // Otherwise, render the wizard flow (input, loading, skeleton)
  return (
    <div className="min-h-screen bg-cheddar-gray-50">
      {/* Navigation Header */}
      <div className="border-b border-cheddar-gray-200 bg-white">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-4 flex items-center justify-between">
          <div className="ml-auto flex items-center gap-4">
            <button
              onClick={handleBackToTemplateSelection}
              className="text-cheddar-orange hover:text-cheddar-orange-hover transition-colors text-sm font-medium"
            >
              Back to Dashboard
            </button>
            <img src="/Logo.png" alt="CheddarUp" className="h-8 w-auto" />
          </div>
        </div>
      </div>
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-12">
        <Suspense fallback={<div>Loading...</div>}>
          {loadingPhase === 'idle' && (
            <InputStep
              onSubmit={handleInputSubmit}
              isLoading={false}
              initialPrompt={userPrompt}
              error={error}
              onRetry={handleRetry}
            />
          )}
          {loadingPhase === 'cube' && (
            <div className="max-w-4xl mx-auto">
              <div className="mb-8 flex items-center justify-center">
                <div className="relative bg-white border border-cheddar-gray-300 rounded-lg px-6 py-3 shadow-sm">
                  <span className="text-sm text-cheddar-gray-700">{userPrompt}</span>
                  <button
                    className="absolute -right-2 -top-2 w-6 h-6 bg-cheddar-gray-700 text-white rounded-full flex items-center justify-center"
                  >
                    <X className="w-4 h-4" />
                  </button>
                </div>
              </div>
              <div className="text-center mb-8">
                <p className="text-base text-cheddar-gray-700">
                  Here is an example of a group gift collection for a wedding gift
                </p>
              </div>
              <div className="flex justify-center py-24">
                <CubeLoader />
              </div>
            </div>
          )}
          {loadingPhase === 'skeleton' && (
            <div className="max-w-4xl mx-auto">
              <div className="mb-8 flex items-center justify-center">
                <div className="relative bg-white border-cheddar-gray-300 rounded-lg px-6 py-3 shadow-sm">
                  <span className="text-sm text-cheddar-gray-700">{userPrompt}</span>
                  <button
                    className="absolute -right-2 -top-2 w-6 h-6 bg-cheddar-gray-700 text-white rounded-full flex items-center justify-center"
                  >
                    <X className="w-4 h-4" />
                  </button>
                </div>
              </div>
              <div className="text-center mb-8">
                <p className="text-base text-cheddar-gray-700">
                  Here is an example of a group gift collection for a wedding gift
                </p>
              </div>
              <SkeletonLoader />
            </div>
          )}
        </Suspense>
      </div>
    </div>
  );
}

function App() {
  return (
    <QueryClientProvider client={queryClient}>
      <CollectionWizard />
      <ReactQueryDevtools initialIsOpen={false} />
    </QueryClientProvider>
  );
}

export default App;
